---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skylla-config
data:
  skylla.conf: |
    gerrit:
      url: https://gerrit.dev.pekao.com.pl
      user: skylla
      password: ${GERRIT_PASSWORD}
    jira:
      url: https://jira.cn.in.pekao.com.pl
      user: jira_tech_gerrit
      password: ${JIRA_PASSWORD}
    artifactory:
      url: https://pakiety.dev.pekao.com.pl
      user: skylla
      password: ${ARTIFACTORY_PASSWORD}
    sentry:
      dsn: ${SENTRY_DSN}
    ca_certs: /etc/ssl/certs/ca-certificates.crt
